name: SimpleCICD_CD
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: 101
      source:  Revati014.CICD  # Must match the CI pipeline namee
      trigger:
        branches:
          include:
            - main
            - SimpleCICD_CD

pool:
  name: SelfHosted
  demands:
    - Agent.Name -equals Agennt

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
